const MoviesReviews=[
    {"id": 1, "comment": "Fantastic movie! The plot and characters were captivating. I was on the edge of my seat the entire time.", "rating": 4.5},
    {"id": 2, "comment": "Enjoyed watching it, though the ending left me wanting more. The character development was well-done.", "rating": 3.8},
    {"id": 3, "comment": "Absolutely brilliant! The cinematography and acting were top-notch. I can't wait to watch it again.", "rating": 5.0},
    {"id": 4, "comment": "A great film with a surprising twist at the end. The pacing kept me engaged from start to finish.", "rating": 4.2},
    {"id": 5, "comment": "Solid performances and a compelling storyline. I particularly enjoyed the dynamic between the main characters.", "rating": 4.0},
    {"id": 6, "comment": "Not my cup of tea. The pacing felt a bit off, and some scenes seemed unnecessary.", "rating": 2.5},
    {"id": 7, "comment": "An emotional rollercoaster! The ending brought tears to my eyes. The soundtrack complemented the mood perfectly.", "rating": 4.8},
    {"id": 8, "comment": "The special effects were amazing, but the story lacked depth. I expected more from the plot.", "rating": 3.5},
    {"id": 9, "comment": "A must-watch! I was on the edge of my seat throughout. The suspense was masterfully executed.", "rating": 4.7},
    {"id": 10, "comment": "Interesting concept, but the execution fell short for me. Some parts felt forced and disconnected.", "rating": 3.0},
    {"id": 11, "comment": "Laugh-out-loud funny! Perfect for a movie night with friends. The humor was clever and well-timed.", "rating": 4.5},
    {"id": 12, "comment": "Visually stunning, but the plot left me confused. I had difficulty following some of the narrative.", "rating": 3.2},
    {"id": 13, "comment": "Incredible performances and a powerful message. The emotional impact lingered long after the credits rolled.", "rating": 4.9},
    {"id": 14, "comment": "A classic! I could watch it over and over again. The timeless appeal never gets old.", "rating": 5.0},
    {"id": 15, "comment": "The soundtrack was amazing! It added so much to the atmosphere. Each musical piece was carefully chosen.", "rating": 4.6},
    {"id": 16, "comment": "Not what I expected, but pleasantly surprised. The unexpected twists kept me engaged.", "rating": 3.8},
    {"id": 17, "comment": "An intense thriller that kept me guessing until the end. The suspense was palpable.", "rating": 4.7},
    {"id": 18, "comment": "A bit too predictable for my taste, but still enjoyable. The predictable moments were balanced by strong performances.", "rating": 3.5},
    {"id": 19, "comment": "Heartwarming and beautifully crafted. The emotional resonance was felt throughout the film.", "rating": 4.8},
    {"id": 20, "comment": "The plot twists were mind-blowing! Didn't see them coming. Each twist added layers to the narrative.", "rating": 4.9},
    {"id": 21, "comment": "A solid entry in the genre. Great action sequences. The action was well-choreographed and visually stunning.", "rating": 4.0},
    {"id": 22, "comment": "Could have been better. The dialogue felt forced at times. Some dialogues seemed unnatural and forced.", "rating": 2.8},
    {"id": 23, "comment": "An emotional journey that left me reflecting for days. The characters' emotional arcs were well-developed.", "rating": 4.5},
    {"id": 24, "comment": "The characters were relatable, and the story was compelling. Each character had a unique and relatable story.", "rating": 4.2},
    {"id": 25, "comment": "Not for everyone, but I appreciated the unique storytelling. The unconventional storytelling added a layer of intrigue.", "rating": 3.7},
    {"id": 26, "comment": "A cinematic masterpiece! Every frame was a work of art. The visual aesthetics were breathtaking.", "rating": 5.0},
    {"id": 27, "comment": "Meh. It didn't live up to the hype for me. The hype created certain expectations that the film didn't meet.", "rating": 2.0},
    {"id": 28, "comment": "Thrilling from start to finish. I couldn't look away. The suspense was maintained consistently.", "rating": 4.6},
    {"id": 29, "comment": "The humor was a bit forced, but the action was great. Some comedic moments felt unnatural.", "rating": 3.5},
    {"id": 30, "comment": "Captivating from the first scene. I was hooked. The opening scene set the tone for the entire film.", "rating": 4.8},
    {"id": 31, "comment": "The cinematography was outstanding! A visual feast. Each frame was meticulously composed.", "rating": 4.9},
    {"id": 32, "comment": "A feel-good movie with a positive message. The uplifting message resonated throughout the film.", "rating": 4.0},
    {"id": 33, "comment": "The suspense was killing me! A great suspense thriller. The tension was maintained throughout.", "rating": 4.7},
    {"id": 34, "comment": "The storyline was a bit cliché, but the performances saved it. Strong performances elevated the familiar plot.", "rating": 3.2},
    {"id": 35, "comment": "A wild ride! The twists and turns kept me on the edge of my seat. The unpredictable nature added excitement.", "rating": 4.5},
    {"id": 36, "comment": "I didn't connect with the characters, but the visuals were stunning. The visual spectacle compensated for the lack of emotional connection.", "rating": 3.6},
    {"id": 37, "comment": "An epic adventure! Perfect for fans of the genre. The adventure elements were well-executed.", "rating": 4.7},
    {"id": 38, "comment": "A thought-provoking film that stayed with me long after it ended. The themes lingered in my thoughts.", "rating": 4.8},
    {"id": 39, "comment": "A bit slow-paced, but the character development was worth it. The slow pace allowed for meaningful", "rating": 4.8},
    {"id": 40, "comment": "Engaging storyline with well-developed characters.", "rating": 4.5},
    {"id": 41, "comment": "Unexpected twists kept me hooked till the end.", "rating": 4.2},
    {"id": 42, "comment": "Great cinematography and attention to detail.", "rating": 4.7},
    {"id": 43, "comment": "The plot had me on the edge of my seat throughout.", "rating": 4.6},
    {"id": 44, "comment": "Wonderful performances by the entire cast.", "rating": 4.8},
    {"id": 45, "comment": "A perfect blend of drama and suspense.", "rating": 4.4},
    {"id": 46, "comment": "Beautifully crafted narrative with emotional depth.", "rating": 4.6},
    {"id": 47, "comment": "Thought-provoking and intellectually stimulating.", "rating": 4.3},
    {"id": 48, "comment": "Excellent direction and storytelling.", "rating": 4.7},
    {"id": 49, "comment": "Captivating from start to finish.", "rating": 4.5},
    {"id": 50, "comment": "Intriguing plot twists that kept me guessing.", "rating": 4.2},
    {"id": 51, "comment": "Strong character arcs and meaningful dialogue.", "rating": 4.8},
    {"id": 52, "comment": "A cinematic masterpiece with powerful performances.", "rating": 4.9},
    {"id": 53, "comment": "Impressive attention to visual and auditory details.", "rating": 4.7},
    {"id": 54, "comment": "The narrative unfolds seamlessly, keeping you captivated.", "rating": 4.6},
    {"id": 55, "comment": "Emotionally resonant and thoughtfully executed.", "rating": 4.5},
    {"id": 56, "comment": "Well-developed characters make the story relatable.", "rating": 4.4},
    {"id": 57, "comment": "A must-watch for fans of complex storytelling.", "rating": 4.6},
    {"id": 58, "comment": "Every scene contributes to the overall narrative.", "rating": 4.7},
    {"id": 59, "comment": "Compelling and immersive, with a strong emotional impact.", "rating": 4.8},
    {"id": 60, "comment": "Highly recommended for its unique and original plot.", "rating": 4.5},
    {"id": 61, "comment": "Engrossing plot development with well-crafted dialogues.", "rating": 4.3},
    {"id": 62, "comment": "Cinematic excellence with a captivating storyline.", "rating": 4.9},
    {"id": 63, "comment": "The pacing allows for a deep connection with the characters.", "rating": 4.6},
    {"id": 64, "comment": "An impressive blend of suspense and drama.", "rating": 4.7},
    {"id": 65, "comment": "Character relationships add layers to the overall narrative.", "rating": 4.8},
    {"id": 66, "comment": "Attention-grabbing from the very first scene.", "rating": 4.4},
    {"id": 67, "comment": "A cinematic journey that lingers in your thoughts.", "rating": 4.7},
    {"id": 68, "comment": "Well-executed plot with satisfying resolution.", "rating": 4.5},
    {"id": 69, "comment": "Engaging and thought-provoking storyline.", "rating": 4.6},
    {"id": 70, "comment": "Decent storyline with room for improvement.", "rating": 3.2},
    {"id": 71, "comment": "A fair attempt, but lacked a compelling narrative.", "rating": 2.8},
    {"id": 72, "comment": "Some engaging moments, but overall a bit mediocre.", "rating": 3.5},
    {"id": 73, "comment": "Average performances, didn't leave a lasting impression.", "rating": 3.0},
    {"id": 74, "comment": "An okay watch, but expected more from the plot.", "rating": 3.3},
    {"id": 75, "comment": "Storyline was average, nothing stood out.", "rating": 3.1},
    {"id": 76, "comment": "Decent character development, but lacked depth.", "rating": 3.4},
    {"id": 77, "comment": "A mediocre attempt at storytelling.", "rating": 2.9},
    {"id": 78, "comment": "Characters were average, needed more complexity.", "rating": 3.2},
    {"id": 79, "comment": "Expected more depth in the plot, felt a bit shallow.", "rating": 3.3},
    {"id": 80, "comment": "Didn't quite meet expectations, and had no redeeming qualities.", "rating": 3.1},
    {"id": 81, "comment": "Storyline lacked originality, felt somewhat generic.", "rating": 3.5},
    {"id": 82, "comment": "An average viewing experience, neither good nor bad.", "rating": 3.0},
    {"id": 83, "comment": "Performance was mediocre, lacked emotional impact.", "rating": 3.2},
    {"id": 84, "comment": "Boring plot, didn't offer any surprises.", "rating": 3.4},
    {"id": 85, "comment": "Characters were forgettable, lacked complexity.", "rating": 3.1},
    {"id": 86, "comment": "An average attempt at storytelling, didn't stand out.", "rating": 3.3},
    {"id": 87, "comment": "Didn't live up to expectations, fell short.", "rating": 2.8},
    {"id": 88, "comment": "A standard storyline, nothing extraordinary.", "rating": 3.2},
    {"id": 89, "comment": "Average performances, didn't leave a lasting impact.", "rating": 3.0},
    {"id": 90, "comment": "Decent execution, but lacked originality.", "rating": 3.4},
    {"id": 91, "comment": "A fair attempt, but the plot needed more depth.", "rating": 3.1},
    {"id": 92, "comment": "Average character development, didn't feel fully realized.", "rating": 3.3},
    {"id": 93, "comment": "Storyline lacked depth, felt a bit surface-level.", "rating": 3.2},
    {"id": 94, "comment": "An average film, nothing remarkable.", "rating": 3.0},
    {"id": 95, "comment": "Expected more substance in the plot, felt a bit thin.", "rating": 3.4},
    {"id": 96, "comment": "A passable attempt, but didn't leave a strong impression.", "rating": 3.1},
    {"id": 97, "comment": "Average performances, needed more intensity.", "rating": 3.3},
    {"id": 98, "comment": "An ordinary storyline with room for improvement.", "rating": 3.2},
    {"id": 99, "comment": "Didn't quite meet expectations, felt average.", "rating": 3.0},
    {"id": 100, "comment": "A standard viewing experience, neither good nor bad.", "rating": 3.5},
    {"id": 101, "comment": "Disappointing plot with predictable twists. Wouldn't recommend.", "rating": 2.3},
    {"id": 102, "comment": "Lackluster characters and a tedious storyline. A letdown.", "rating": 2.1},
    {"id": 103, "comment": "Unengaging narrative that failed to capture my interest.", "rating": 2.0},
    {"id": 104, "comment": "Poorly written with flat characters. Regrettable reading experience.", "rating": 1.8},
    {"id": 105, "comment": "Slow-paced and uneventful. Couldn't connect with the story.", "rating": 2.2},
    {"id": 106, "comment": "Shallow characters and a cliche-ridden plot. A waste of time.", "rating": 1.9},
    {"id": 107, "comment": "Confusing storyline with inconsistent character development.", "rating": 2.1},
    {"id": 108, "comment": "Uninspired writing and a lack of originality. A forgettable read.", "rating": 1.7},
    {"id": 109, "comment": "Dull and uninspiring. Failed to engage me from the start.", "rating": 2.0},
    {"id": 110, "comment": "Predictable and formulaic. The plot lacked depth.", "rating": 1.8},
    {"id": 111, "comment": "Disjointed narrative with underdeveloped characters. A disappointment.", "rating": 2.2},
    {"id": 112, "comment": "Tedious and monotonous storytelling. Couldn't finish it.", "rating": 1.6},
    {"id": 113, "comment": "Amazing characters and a lot of emotional depth.", "rating": 4.0},
    {"id": 114, "comment": "Confusing plot with unresolved threads. Left me unsatisfied.", "rating": 2.1},
    {"id": 115, "comment": "Overhyped and underwhelming. Didn't live up to expectations.", "rating": 1.9},
    {"id": 116, "comment": "Bland characters and a forgettable storyline.", "rating": 1.7},
    {"id": 117, "comment": "Incoherent narrative and poorly developed characters.", "rating": 1.8},
    {"id": 118, "comment": "A struggle to get through. The plot lacked substance.", "rating": 1.6},
    {"id": 119, "comment": "Disjointed and uninteresting. Regret picking this movie.", "rating": 2.0},
    {"id": 120, "comment": "Unimpressive and forgettable. Not worth the time.", "rating": 1.7},
    {"id": 121, "comment": "Predictable and formulaic. Disappointing.", "rating": 2.1},
    {"id": 122, "comment": "Lacked depth and failed to engage. Wouldn't recommend.", "rating": 1.9},
    {"id": 123, "comment": "Contrived plot with uninteresting characters. A letdown.", "rating": 1.8},
    {"id": 124, "comment": "Unconvincing dialogue and weak character motivations.", "rating": 1.6},
    {"id": 125, "comment": "Underwhelming and predictable. Didn't meet my expectations.", "rating": 1.9},
    {"id": 126, "comment": "Failed to hold my attention. The plot lacked intrigue.", "rating": 1.7},
    {"id": 127, "comment": "A disappointing read with a lackluster storyline.", "rating": 1.8},
    {"id": 128, "comment": "Poorly executed plot with uninteresting characters.", "rating": 1.6},
    {"id": 129, "comment": "Unimpressive writing style and a forgettable narrative.", "rating": 1.9},
    {"id": 130, "comment": "Flat characters and a predictable storyline. Not recommended.", "rating": 2.0},
    {"id": 131, "comment": "Uninspiring characters and a lack of depth.", "rating": 1.8},
    {"id": 132, "comment": "A tedious narrative that failed to engage.", "rating": 1.7},
    {"id": 133, "comment": "Shallow characters and an unremarkable plot.", "rating": 1.6},
    {"id": 134, "comment": "A forgettable read with uninspired writing.", "rating": 1.9},
    {"id": 135, "comment": "Predictable twists and lackluster character development.", "rating": 2.0},
    {"id": 136, "comment": "Flat and uninteresting. Wouldn't recommend.", "rating": 1.7},
    {"id": 137, "comment": "Disappointing from start to finish. A letdown.", "rating": 1.8},
    {"id": 138, "comment": "Lackluster storytelling with forgettable characters.", "rating": 1.6},
    {"id": 139, "comment": "Unimpressive plot and underwhelming character arcs.", "rating": 1.9},
    {"id": 140, "comment": "A regrettable choice with a lackluster plot.", "rating": 1.7},
    {"id": 141, "comment": "Weak character development and a predictable storyline.", "rating": 1.8},
    {"id": 142, "comment": "Incoherent and unconvincing. Disappointing.", "rating": 1.6},
    {"id": 143, "comment": "A lackluster read with uninspiring characters.", "rating": 1.9},
    {"id": 144, "comment": "Predictable and uninspired. Wouldn't recommend.", "rating": 1.7},
    {"id": 145, "comment": "Disappointing plot and unengaging characters.", "rating": 1.8},
    {"id": 146, "comment": "Lackluster storytelling with an unremarkable plot.", "rating": 1.6},
    {"id": 147, "comment": "Unimpressive from start to finish. A letdown.", "rating": 1.9},
    {"id": 148, "comment": "Weak character arcs and a predictable narrative.", "rating": 1.7},
    {"id": 149, "comment": "Flat and uninspiring. Regrettable reading experience.", "rating": 1.8},
    {"id": 150, "comment": "Predictable twists and a lack of depth. Not recommended.", "rating": 1.6}
]
export default MoviesReviews;